-- MySQL Script generated by MySQL Workbench
-- Thu Sep  5 14:18:58 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


CREATE SCHEMA IF NOT EXISTS `template` DEFAULT CHARACTER SET utf8 ;
USE `template` ;
-- -----------------------------------------------------
-- Table `template`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `template`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `passwordHash` VARCHAR(255) NULL,
  `language` VARCHAR(45) NULL,
  `refreshToken` VARCHAR(300) NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `patronymic` VARCHAR(45) NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `template`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `template`.`Role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `template`.`UserRole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `template`.`UserRole` (
  `userId` INT NOT NULL,
  `roleId` INT NOT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`userId`, `roleId`),
  INDEX `fk_UserPosition_Position1_idx` (`roleId` ASC),
  INDEX `fk_UserPosition_User1_idx` (`userId` ASC),
  CONSTRAINT `fk_UserPosition_User1`
    FOREIGN KEY (`userId`)
    REFERENCES `template`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserPosition_Position1`
    FOREIGN KEY (`roleId`)
    REFERENCES `template`.`Role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `template`.`Page`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `template`.`Page` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
